[View in Colaboratory](https://colab.research.google.com/github/Carlitoshsh/-ML-Lab2/blob/master/Lab_2_Item_6.ipynb)

In [0]:
# Import pandas library
import pandas as pd

In [68]:
#Rap Biggie Smalls
url_data_biggie = "https://raw.githubusercontent.com/NoahLidell/math-of-intelligence/master/probability_theory/biggie_lyrics.csv"
biggie_df = pd.read_csv(url_data_biggie, usecols=[1], encoding='latin-1', header=None)
biggie_df.columns = ["lyrics"]
biggie_df.head()

lyrics
0  Fuck all you hoes\nGet a grip motherfucker.\nY...
1  As I grab the glock, put it to your headpiece\...
2  I don't wanna live no mo'\nSometimes I hear de...
3  To all the ladies in the place with style and ...
4  Nineteen-seventy somethin', nigga I don't swea...

In [69]:
url_data_pac = "https://raw.githubusercontent.com/NoahLidell/math-of-intelligence/master/probability_theory/2pac_lyrics.csv"
pac_df = pd.read_csv(url_data_pac, usecols=[1], encoding='latin-1', header=None)
pac_df.columns = ["lyrics"]
pac_df.head()

lyrics
0  Little something for my godson Elijah\nAnd a l...
1  Yo Mo Bee mayn! Drop that shit!\nYou know what...
2  Rest in peace to my motherfucker Biggy Smallz\...
3  Makaveli in this, Killuminati\nAll through you...
4  It's just me against the world\nNothin' to los...

In [70]:
biggie_df["lyrics"] = biggie_df["lyrics"].map(lambda x: x.lower())
biggie_df.head()

lyrics
0  fuck all you hoes\nget a grip motherfucker.\ny...
1  as i grab the glock, put it to your headpiece\...
2  i don't wanna live no mo'\nsometimes i hear de...
3  to all the ladies in the place with style and ...
4  nineteen-seventy somethin', nigga i don't swea...

In [71]:
pac_df["lyrics"] = pac_df["lyrics"].map(lambda x: x.lower())
pac_df.head()

lyrics
0  little something for my godson elijah\nand a l...
1  yo mo bee mayn! drop that shit!\nyou know what...
2  rest in peace to my motherfucker biggy smallz\...
3  makaveli in this, killuminati\nall through you...
4  it's just me against the world\nnothin' to los...

In [72]:
# Convert a collection of text documents to a matrix of token counts
# http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
# http://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction
# to allow one letter words count_vect = CountVectorizer(token_pattern = r"(?u)\b\w+\b")
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(token_pattern = r"(?u)\b\w+\b") 
counts2pac = count_vect.fit_transform(pac_df["lyrics"])

print(counts2pac)


  (0, 1511)	1
  (0, 745)	1
  (0, 116)	1
  (0, 451)	1
  (0, 1270)	1
  (0, 1378)	1
  (0, 300)	1
  (0, 1074)	2
  (0, 1065)	1
  (0, 1744)	2
  (0, 634)	1
  (0, 336)	1
  (0, 406)	1
  (0, 1698)	1
  (0, 763)	1
  (0, 1462)	1
  (0, 274)	1
  (0, 1291)	1
  (0, 1539)	1
  (0, 1713)	2
  (0, 531)	1
  (0, 921)	1
  (0, 1093)	1
  (0, 800)	1
  (0, 462)	1
  :	:
  (15, 808)	1
  (15, 421)	1
  (15, 599)	3
  (15, 1688)	5
  (15, 967)	3
  (15, 1707)	2
  (15, 929)	1
  (15, 889)	2
  (15, 215)	2
  (15, 435)	3
  (15, 1767)	2
  (15, 102)	1
  (15, 899)	1
  (15, 1562)	1
  (15, 853)	1
  (15, 1522)	1
  (15, 1075)	2
  (15, 1589)	4
  (15, 633)	2
  (15, 787)	2
  (15, 1556)	6
  (15, 1313)	2
  (15, 11)	4
  (15, 50)	7
  (15, 582)	1


In [73]:
countsbiggie = count_vect.fit_transform(biggie_df["lyrics"])  
print(countsbiggie)

  (0, 852)	1
  (0, 604)	1
  (0, 1024)	1
  (0, 1026)	1
  (0, 896)	1
  (0, 824)	1
  (0, 1792)	1
  (0, 1368)	1
  (0, 1301)	1
  (0, 1140)	1
  (0, 1901)	1
  (0, 982)	1
  (0, 1378)	1
  (0, 420)	1
  (0, 85)	1
  (0, 1739)	1
  (0, 297)	1
  (0, 1513)	1
  (0, 426)	1
  (0, 1942)	1
  (0, 147)	1
  (0, 1084)	1
  (0, 322)	1
  (0, 1918)	1
  (0, 1936)	1
  :	:
  (15, 1843)	3
  (15, 1417)	8
  (15, 874)	7
  (15, 1018)	3
  (15, 920)	1
  (15, 57)	4
  (15, 1126)	5
  (15, 1574)	4
  (15, 897)	2
  (15, 1908)	2
  (15, 1194)	6
  (15, 1188)	1
  (15, 854)	7
  (15, 1249)	1
  (15, 843)	19
  (15, 1059)	3
  (15, 1722)	5
  (15, 1723)	19
  (15, 1772)	11
  (15, 873)	4
  (15, 16)	8
  (15, 797)	2
  (15, 1961)	4
  (15, 46)	3
  (15, 653)	3


In [74]:
print("2pac, documents and words",counts2pac.shape)
print("biggie, documents and words",countsbiggie.shape)

('2pac, documents and words', (16, 1774))
('biggie, documents and words', (16, 1968))


In [75]:
# https://stackoverflow.com/questions/28064634/random-state-pseudo-random-numberin-scikit-learn
from sklearn.model_selection import train_test_split
X_train_biggie, X_test_biggie, y_train_biggie, y_test_biggie = train_test_split(countsbiggie, biggie_df["lyrics"], test_size=0.1, random_state=69) 

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB().fit(X_train_biggie, y_train_biggie)  

import numpy as np
predicted = model.predict(X_test_biggie)
print(np.mean(predicted == y_test_biggie))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test_biggie, predicted))

0.0
[[0 0 0]
 [1 0 0]
 [1 0 0]]


In [76]:
# https://stackoverflow.com/questions/28064634/random-state-pseudo-random-numberin-scikit-learn
from sklearn.model_selection import train_test_split
X_train_2pac, X_test_2pac, y_train_2pac, y_test_2pac = train_test_split(counts2pac, pac_df["lyrics"], test_size=0.1, random_state=69) 

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB().fit(X_train_2pac, y_train_2pac)  

import numpy as np
predicted = model.predict(X_test_2pac)
print(np.mean(predicted == y_test_2pac))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test_2pac, predicted))

0.0
[[0 0 1 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]]


In [0]:
def performance_test(my_size, my_count, columnLyrics):
  per = 0
  for i in range(0,10):
      X_train, X_test, y_train, y_test = train_test_split(my_count, columnLyrics, test_size=my_size) 
      model = MultinomialNB().fit(X_train, y_train) 

      import numpy as np
      predicted = model.predict(X_test)
      print(np.mean(predicted == y_test))
      per += np.mean(predicted == y_test)

      from sklearn.metrics import confusion_matrix
      print(confusion_matrix(y_test, predicted))

  print "average performance"
  print per/10.0

In [78]:
performance_test(0.1,counts2pac, pac_df["lyrics"])

0.0
[[0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]]
0.0
[[0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [1 0 0 0]]
0.0
[[0 0 0]
 [1 0 0]
 [1 0 0]]
0.0
[[0 0 1]
 [0 0 1]
 [0 0 0]]
0.0
[[0 0 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 1 0]]
0.0
[[0 0 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 0 0]]
0.0
[[0 0 0]
 [1 0 0]
 [1 0 0]]
0.0
[[0 0 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 0 0]]
0.0
[[0 0 1]
 [0 0 1]
 [0 0 0]]
0.0
[[0 0 0]
 [1 0 0]
 [1 0 0]]
average performance
0.0


In [79]:
performance_test(0.2,counts2pac, pac_df["lyrics"])

0.0
[[0 0 0 0 1 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
0.0
[[0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]]
0.0
[[0 0 1 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]
 [0 0 1 0 0 0]]
0.0
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 0 0]]
0.0
[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]]
0.0
[[0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]]
0.0
[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]]
0.0
[[0 0 0 1 0 0]
 [0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 1 0 0]]
0.0
[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]]
0.0
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]]
average perfo

In [80]:
performance_test(0.5,counts2pac, pac_df["lyrics"])

0.0
[[0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]]
0.0
[[0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]]
0.0
[[0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]]
0.0
[[0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0

In [81]:
performance_test(0.1,countsbiggie, biggie_df["lyrics"])

0.0
[[0 1 0]
 [0 0 0]
 [0 1 0]]
0.0
[[0 1 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]]
0.0
[[0 1 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]]
0.0
[[0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]]
0.0
[[0 1 0]
 [0 0 0]
 [0 1 0]]
0.0
[[0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [1 0 0 0]]
0.0
[[0 1 0]
 [0 0 0]
 [0 1 0]]
0.0
[[0 1 0]
 [0 0 0]
 [0 1 0]]
0.0
[[0 1 0]
 [0 0 0]
 [0 1 0]]
0.0
[[0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [1 0 0 0]]
average performance
0.0


In [82]:
performance_test(0.2,countsbiggie, biggie_df["lyrics"])

0.0
[[0 1 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 1 0 0 0 0]]
0.0
[[0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0]]
0.0
[[0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]]
0.0
[[0 0 0 0 1 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 0 0 0]]
0.0
[[0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]]
0.0
[[0 0 1 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]]
0.0
[[0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0]]
0.0
[[0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [1 0 0 0 0 0]
 [0 0 1 0 0 0]]
0.0
[[0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 1 0]]
0.0
[[0 0 0 0 0 0]
 [0 0 0 0 

In [83]:
performance_test(0.5, countsbiggie, biggie_df["lyrics"])

0.0
[[0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]]
0.0
[[0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]]
0.0
[[0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]]
0.0
[[0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]]
0.0
[[0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 