[View in Colaboratory](https://colab.research.google.com/github/Carlitoshsh/-ML-Lab2/blob/master/Lab_2_Item_4,5.ipynb)

### SPAM Detection - The Naive Bayes Algorithm in Python with Scikit-Learn 
D. Shahrokhian
https://stackabuse.com/the-naive-bayes-algorithm-in-python-with-scikit-learn/

**Conclusion**

## Item 4
Shahrokian has better performance for cities training set that Lidell

## Item 5
Bernoulli has better performance depending on test_size than Multinomial.  

In [39]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [40]:
import pandas as pd

# SMS Spam Collection Data Set
# https://archive.ics.uci.edu/ml/datasets/sms+spam+collection
# For first time, you can connect Google Drive with Colaboratory
#from google.colab import drive
#drive.mount('/content/gdrive')
df = pd.read_table('/content/gdrive/My Drive/Colab Notebooks/TableLab2.txt',  
                   sep=':', 
                   header=None,
                   names=['c = China?', 'words in document'])
df.head()
#df['words in document']

c = China?         words in document
0        yes   Chinese Beijing Chinese
1        yes  Chinese Chinese Shanghai
2        yes             Chinese Macao
3         no       Tokyo Japan Chinese
4        yes             Taipei Taiwan

In [41]:
df['c = China?'] = df['c = China?'].map({'no': 0, 'yes': 1})
df['words in document'] = df['words in document'].map(lambda x: x.lower())
df.head()

c = China?         words in document
0           1   chinese beijing chinese
1           1  chinese chinese shanghai
2           1             chinese macao
3           0       tokyo japan chinese
4           1             taipei taiwan

In [42]:
# Convert a collection of text documents to a matrix of token counts
# http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html
# http://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction
# to allow one letter words count_vect = CountVectorizer(token_pattern = r"(?u)\b\w+\b")
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(token_pattern = r"(?u)\b\w+\b") 
counts = count_vect.fit_transform(df['words in document'])  
print counts

  (0, 0)	1
  (0, 1)	2
  (1, 6)	1
  (1, 1)	2
  (2, 3)	1
  (2, 1)	1
  (3, 2)	1
  (3, 9)	1
  (3, 1)	1
  (4, 8)	1
  (4, 7)	1
  (5, 8)	1
  (5, 3)	1
  (5, 6)	1
  (6, 5)	1
  (6, 2)	1
  (7, 4)	1
  (7, 5)	1
  (7, 8)	1


In [43]:
counts.shape

(8, 10)

In [44]:
# https://stackoverflow.com/questions/28064634/random-state-pseudo-random-numberin-scikit-learn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(counts, df['c = China?'], test_size=0.1, random_state=69) 

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB().fit(X_train, y_train)  

import numpy as np
predicted = model.predict(X_test)
print(np.mean(predicted == y_test))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predicted))

0.0
[[0 0]
 [1 0]]


In [0]:
def performance_test(my_size, my_count, columnLyrics):
  per = 0
  for i in range(0,10):
      X_train, X_test, y_train, y_test = train_test_split(my_count, columnLyrics, test_size=my_size) 
      model = MultinomialNB().fit(X_train, y_train) 

      import numpy as np
      predicted = model.predict(X_test)
      print(np.mean(predicted == y_test))
      per += np.mean(predicted == y_test)

      from sklearn.metrics import confusion_matrix
      print(confusion_matrix(y_test, predicted))

  print "average performance"
  print per/10.0

In [46]:
performance_test(0.1,counts, df['c = China?'])

1.0
[[1]]
1.0
[[1]]
1.0
[[1]]
0.0
[[0 1]
 [0 0]]
0.0
[[0 0]
 [1 0]]
1.0
[[1]]
1.0
[[1]]
0.0
[[0 1]
 [0 0]]
0.0
[[0 1]
 [0 0]]
1.0
[[1]]
average performance
0.6


In [47]:
performance_test(0.2,counts, df['c = China?'])

0.5
[[0 1]
 [0 1]]
1.0
[[1 0]
 [0 1]]
0.5
[[0 0]
 [1 1]]
1.0
[[1 0]
 [0 1]]
0.5
[[0 1]
 [0 1]]
0.5
[[0 1]
 [0 1]]
0.5
[[0 1]
 [0 1]]
0.5
[[0 0]
 [1 1]]
0.5
[[0 0]
 [1 1]]
0.5
[[0 1]
 [0 1]]
average performance
0.6


In [48]:
performance_test(0.5,counts, df['c = China?'])

0.75
[[1 0]
 [1 2]]
0.5
[[1 0]
 [2 1]]
0.25
[[0 1]
 [2 1]]
0.5
[[0 1]
 [1 2]]
0.5
[[0 2]
 [0 2]]
0.75
[[1 1]
 [0 2]]
0.75
[[1 0]
 [1 2]]
0.75
[[1 1]
 [0 2]]
0.75
[[1 0]
 [1 2]]
1.0
[[1 0]
 [0 3]]
average performance
0.65


**Bernoulli**

In [0]:
from sklearn.naive_bayes import BernoulliNB

def performance_test_Bernoulli(my_size, my_count, columnLyrics):
  per = 0
  for i in range(0,10):
      X_train, X_test, y_train, y_test = train_test_split(my_count, columnLyrics, test_size=my_size) 
      model = BernoulliNB().fit(X_train, y_train) 

      import numpy as np
      predicted = model.predict(X_test)
      print(np.mean(predicted == y_test))
      per += np.mean(predicted == y_test)

      from sklearn.metrics import confusion_matrix
      print(confusion_matrix(y_test, predicted))

  print "average performance Bernoulli"
  print per/10.0

In [50]:
performance_test_Bernoulli(0.1,counts, df['c = China?'])

1.0
[[1]]
1.0
[[1]]
1.0
[[1]]
1.0
[[1]]
1.0
[[1]]
1.0
[[1]]
1.0
[[1]]
1.0
[[1]]
1.0
[[1]]
1.0
[[1]]
average performance Bernoulli
1.0


In [51]:
performance_test_Bernoulli(0.2,counts, df['c = China?'])

0.5
[[0 1]
 [0 1]]
1.0
[[2]]
1.0
[[2]]
0.5
[[0 1]
 [0 1]]
0.5
[[0 1]
 [0 1]]
1.0
[[1 0]
 [0 1]]
0.5
[[0 1]
 [0 1]]
0.5
[[0 1]
 [0 1]]
1.0
[[1 0]
 [0 1]]
0.5
[[0 1]
 [0 1]]
average performance Bernoulli
0.7


In [52]:
performance_test_Bernoulli(0.5,counts, df['c = China?'])

0.75
[[0 0]
 [1 3]]
1.0
[[1 0]
 [0 3]]
0.75
[[1 1]
 [0 2]]
0.5
[[0 1]
 [1 2]]
1.0
[[1 0]
 [0 3]]
0.75
[[1 1]
 [0 2]]
0.5
[[0 2]
 [0 2]]
0.75
[[0 1]
 [0 3]]
0.5
[[0 2]
 [0 2]]
0.25
[[0 3]
 [0 1]]
average performance Bernoulli
0.675
